languageCode = "en-us"
# baseURL = "https://hackclubrit.github.io/can-you-be-a-freelancer/"
theme = "hello-friend-ng"
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "An Event By HackClub RIT"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
  tag      = "tags"
  category = "categories"

[languages]
  [languages.en]
    title = "Can You Be A Freelancer?"
    subtitle = "An Event By HackClub RIT"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "hackclub-rit"
      logoHomeLink = "/can-you-be-a-freelancer/"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "submissions"
    name       = "Submissions"
    url        = "submissions"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"
  [[params.social]]
    name = "github"
    url = "https://github.com/HackClubRIT/can-you-be-a-freelancer"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/company/hackclubrit/about/"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true